arrayBubbleSortTest: arrayBubbleSortTest.cpp arrayBubbleSort.o
	g++ -o arrayBubbleSortTest arrayBubbleSortTest.cpp arrayBubbleSort.o

arrayBubbleSort.o: arrayBubbleSort.cpp arrayBubbleSort.h
	g++ -c arrayBubbleSort.cpp

clean: 
	rm *.o
